# Generated by Django 4.1.6 on 2023-02-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):    dependencies = [
        ("restaurant", "0002_alter_booking_no_of_guests"),
    ]    # We'll skip this operation as it will be handled by our new migration 0004
    operations = [
    ]
